Initializing the mamimum battery life (T), the number of nodes in the system (N) and the cost of delivery (c)

In [43]:
import random
T = random.randrange(20,30)
N = random.randrange(18,25)
c = float("{:.2f}".format(random.random() * (5 - 3.75) + 3.75))

4.82
20


Initilizing the tij time values

In [44]:
import numpy as np
tij_matrix = [ [ random.randrange(1,5) for i in range(N) ] for j in range(N) ]
tij_matrix = np.triu(tij_matrix, k = 0)
print(tij_matrix)

[[2 3 1 4 3 3 1 1 4 4 3 4 1 4 2 1 3 4 2 4]
 [0 2 2 3 1 4 4 4 1 4 4 2 4 3 1 2 2 3 2 2]
 [0 0 1 1 3 1 2 3 4 4 2 3 3 1 3 4 3 4 4 2]
 [0 0 0 3 1 2 2 1 1 1 1 4 2 1 1 1 4 1 2 3]
 [0 0 0 0 3 3 4 4 1 2 3 3 2 3 1 3 3 1 4 2]
 [0 0 0 0 0 2 3 1 1 4 1 3 2 4 1 2 2 4 4 3]
 [0 0 0 0 0 0 3 1 1 1 3 2 2 2 4 4 2 2 3 1]
 [0 0 0 0 0 0 0 3 1 3 1 1 4 3 3 1 3 1 2 1]
 [0 0 0 0 0 0 0 0 3 1 4 2 3 1 1 2 3 4 2 1]
 [0 0 0 0 0 0 0 0 0 4 3 3 2 4 2 3 2 3 2 3]
 [0 0 0 0 0 0 0 0 0 0 2 3 1 3 2 3 3 3 2 1]
 [0 0 0 0 0 0 0 0 0 0 0 4 2 3 2 3 1 3 4 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 3 3 2 3 4 3 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 4 4 3 2 2 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 2 2 1 2 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 4 4 1 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]]


Initializing the dj delay values at each node

In [45]:
dj_list = []
for i in range(N):
    number = float("{:.2f}".format(random.random() * (0.25 - 0.15) + 0.15))   
    dj_list.append(number)
dj_list[-1] = 0
dj_list[0] = 0
print(dj_list)

[0, 0.22, 0.24, 0.25, 0.18, 0.21, 0.22, 0.2, 0.23, 0.23, 0.18, 0.23, 0.23, 0.22, 0.15, 0.16, 0.24, 0.15, 0.23, 0]
